### ISSUE TITLE
Load game json by overriding JSONdecoder

### ISSUE THREAD

**Issue by mcomella** [zach-r-d/contribgames#1]
We can decode the json directly into a Game instance using [JSONDecoder](http://docs.python.org/3.2/library/json.html?highlight=json.load#json.JSONDecoder), however, there will be some time investment in figuring out how it works, nevermind the potentially added code complexity (for example, I'm not sure how we would handle errors).

Is this something we would be interested in?

**Comment by zach-r-d** [comment]
What do you mean by decoding it directly into a game instance? Using the object_hook parameter?

**Comment by mcomella** [comment]
I believe so - I don't entirely understand the implementation details.

Essentially, we can do the verification taken care of by the `InitVerifier` class in the `JSONDecoder.load()` method, which is a bit cleaner, in my opinion.

**Comment by zach-r-d** [comment]
I understand and agree with the idea; I've moved on to talking about implementation details because we need to ensure what we want to do is in fact possible/appropriate given the library API.

That being said, upon closer inspection I don't think the API has what we need to do this. object_hook is called for every JSON object decoded, not just the top level, so we'd have to do some kind of class hinting at the top level (which would be lame and confusing to JSON file writers).

I think in principle it may be better to have parsing and constructing be separate anyway; especially if we ever need to create Game objects in ways other than by parsing JSON. Feel free to reopen if I missed something and it's totally doable.

**Comment by mcomella** [comment]
> object_hook is called for every JSON object decoded,

I may be mistaken, but I think that means the top-level JSON object, which contains all of the info needed to make a Game in our case.

> I think in principle it may be better to have parsing and constructing be separate anyway; especially if we ever need to create Game objects in ways other than by parsing JSON.

But this makes too much sense; let's not use the JSONDecoder. :P
